/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author coste
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        cmdConvertir.setEnabled(false);
        txtDenominador1.setEditable(true);
        txtDenominador2.setEditable(true);
        txtNumerador1.setEditable(true);
        txtNumerador2.setEditable(true);
        txtEntero1.setEditable(true);
        txtEntero2.setEditable(true);
        txtNumerador1.requestFocusInWindow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDenominador1 = new javax.swing.JTextField();
        txtDenominador4 = new javax.swing.JTextField();
        cmbOperciones = new javax.swing.JComboBox<>();
        txtEntero1 = new javax.swing.JTextField();
        txtEntero2 = new javax.swing.JTextField();
        txtNumerador2 = new javax.swing.JTextField();
        txtDenominador2 = new javax.swing.JTextField();
        txtDenominador3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtNumerador1 = new javax.swing.JTextField();
        txtNumeraor4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cmdLimpiar = new javax.swing.JButton();
        cmdConvertir = new javax.swing.JButton();
        cmdResolver = new javax.swing.JButton();
        txtEntero3 = new javax.swing.JTextField();
        txtNumerador3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mixto");
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDenominador1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 40, -1));

        txtDenominador4.setEditable(false);
        txtDenominador4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtDenominador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 40, -1));

        cmbOperciones.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbOperciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumar", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 70, -1));

        txtEntero1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtEntero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntero1KeyTyped(evt);
            }
        });
        jPanel1.add(txtEntero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        txtEntero2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtEntero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntero2KeyTyped(evt);
            }
        });
        jPanel1.add(txtEntero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 40, -1));

        txtNumerador2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 40, -1));

        txtDenominador2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 40, -1));

        txtDenominador3.setEditable(false);
        txtDenominador3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 40, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 40, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("=");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, -1));

        txtNumerador1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 40, -1));

        txtNumeraor4.setEditable(false);
        txtNumeraor4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtNumeraor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 40, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 40, 10));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        cmdConvertir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdConvertir.setText("Convertir a fraccionario");
        cmdConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        cmdResolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdResolver.setText("Resolver");
        cmdResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResolverActionPerformed(evt);
            }
        });
        jPanel1.add(cmdResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        txtEntero3.setEditable(false);
        txtEntero3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtEntero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 40, -1));

        txtNumerador3.setEditable(false);
        txtNumerador3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(475, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResolverActionPerformed
        // TODO add your handling code here:
        int num1, num2, den1, den2, ent1, ent2;
        Mixto m, m2, m3 = null;
        int op = cmbOperciones.getSelectedIndex();

        num1 = Integer.parseInt(txtNumerador1.getText());
        num2 = Integer.parseInt(txtNumerador2.getText());
        den1 = Integer.parseInt(txtDenominador1.getText());
        den2 = Integer.parseInt(txtDenominador2.getText());
        ent1 = Integer.parseInt(txtEntero1.getText());
        ent2 = Integer.parseInt(txtEntero2.getText());

        try {
            m = new Mixto(ent1, num1, den1);
            m2 = new Mixto(ent2, num2, den2);

            switch (op) {
                case 0:
                    m3 = m.suma(m2);
                    break;
                case 1:
                    m3 = m.resta(m2);
                    break;
                case 2:
                    m3 = m.multiplicacion(m2);
                    break;
                case 3:
                    m3 = m.division(m2);
            }

        } catch (DenominadorCeroException ex) {
            Helper.mensaje(null, "No puede digitar ceros en el denominador", "Error", 2);
        }

        txtEntero3.setText("" + m3.getEntero());
        txtNumerador3.setText("" + m3.getNumerador());
        txtDenominador3.setText("" + m3.getDenominador());

        txtEntero1.setEditable(false);
        txtEntero2.setEditable(false);
        txtNumerador1.setEditable(false);
        txtNumerador2.setEditable(false);
        txtDenominador1.setEditable(false);
        txtDenominador2.setEditable(false);
        cmdResolver.setEnabled(false);
        cmdConvertir.setEnabled(true);
    }//GEN-LAST:event_cmdResolverActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtDenominador4.setText("");
        txtEntero1.setText("");
        txtEntero2.setText("");
        txtEntero3.setText("");
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtNumeraor4.setText("");
        cmbOperciones.setSelectedIndex(0);
        txtEntero1.setEditable(true);
        txtEntero2.setEditable(true);
        txtNumerador1.setEditable(true);
        txtNumerador2.setEditable(true);
        txtDenominador1.setEditable(true);
        txtDenominador2.setEditable(true);
        cmdResolver.setEnabled(true);
        txtEntero1.requestFocusInWindow();

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertirActionPerformed
        // TODO add your handling code here:
        int num, den, num4, den4, ent;

        num = Integer.parseInt(txtNumerador3.getText());
        den = Integer.parseInt(txtDenominador3.getText());
        ent = Integer.parseInt(txtEntero3.getText());

        num4 = (ent * den) + num;
        den4 = den;

        txtNumeraor4.setText("" + num4);
        txtDenominador4.setText("" + den4);
    }//GEN-LAST:event_cmdConvertirActionPerformed

    private void txtEntero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntero1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtEntero1KeyTyped

    private void txtNumerador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador1KeyTyped

    private void txtDenominador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador1KeyTyped

    private void txtEntero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntero2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtEntero2KeyTyped

    private void txtNumerador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador2KeyTyped

    private void txtDenominador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperciones;
    private javax.swing.JButton cmdConvertir;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdResolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtDenominador4;
    private javax.swing.JTextField txtEntero1;
    private javax.swing.JTextField txtEntero2;
    private javax.swing.JTextField txtEntero3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    private javax.swing.JTextField txtNumeraor4;
    // End of variables declaration//GEN-END:variables
}
